acostarodrigo/fermat

DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_actor/asset_user/AssetUserGroupMemberRecord.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_actor/asset_user/AssetUserGroupRecord.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_actor/asset_user/interfaces/ActorAssetUserGroup.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_actor/asset_user/interfaces/ActorAssetUserGroupMember.java

fix #3398 Created Public Interface ActorAssetUserGroup 
fix #3434 Created Public Interface ActorAssetUserGroup
fix #3435 Created Public Interface ActorAssetUserGroupMember 
fix #3436 Implemented Public Interface ActorAssetUserGroupMember 
fix #3437 Implemented Public Interface ActorAssetUserGroup
fix #3436 Modified Public class ActorAssetUserGroupMemberRecord

fixed #3398,  fixed #3434, fixed #3435, fixed #3436, fixed #3437

---

DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_actor/asset_user/interfaces/ActorAssetUserManager.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_sub_app_module/asset_user_community/interfaces/AssetUserCommunitySubAppModuleManager.java
DAP/plugin/actor/fermat-dap-plugin-actor-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/actor/asset/user/developer/bitdubai/version_1/structure/AssetUserActorDao.java
DAP/plugin/sub_app_module/fermat-dap-plugin-sub-app-module-asset-user-community-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/sub_app_module/asset/user/developer/bitdubai/version_1/AssetUserCommunitySubAppModulePluginRoot.java

#3397 DAP - Sub App Module - Asset User Comunity - Implement user groups

---

DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_module/wallet_asset_redeem_point/interfaces/AssetRedeemPointWalletSubAppModule.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_module/wallet_asset_user/interfaces/AssetUserWalletSubAppModuleManager.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_transaction/common/AssetRedeemPointWalletTransactionRecordWrapper.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_transaction/common/AssetUserWalletTransactionRecordWrapper.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_wallet/asset_redeem_point/interfaces/AssetRedeemPointWallet.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_wallet/asset_redeem_point/interfaces/AssetRedeemPointWalletTransactionRecord.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_wallet/asset_user_wallet/interfaces/AssetUserWallet.java
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_wallet/asset_user_wallet/interfaces/AssetUserWalletTransactionRecord.java
DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-asset-appropriation-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/asset_appropiation/developer/bitdubai/version_1/structure/events/AssetAppropriationMonitorAgent.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-assets-user-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/asset/user/developer/bitdubai/version_1/AssetUserWalletPluginRoot.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-assets-user-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/asset/user/developer/bitdubai/version_1/structure/AssetUserWalletImpl.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-assets-user-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/asset/user/developer/bitdubai/version_1/structure/database/AssetUserWalletDao.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-redeem-point-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/wallet/redeem/point/developer/bitdubai/version_1/AssetRedeemPointWalletPluginRoot.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-redeem-point-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/wallet/redeem/point/developer/bitdubai/version_1/structure/AssetRedeemPointWalletImpl.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-redeem-point-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/wallet/redeem/point/developer/bitdubai/version_1/structure/AssetRedeemPointWalletTransactionRecordWrapper.java
DAP/plugin/wallet/fermat-dap-plugin-wallet-redeem-point-wallet-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/wallet/wallet/redeem/point/developer/bitdubai/version_1/structure/database/AssetRedeemPointWalletDao.java
DAP/plugin/wallet_module/fermat-dap-plugin-wallet-module-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/module/asset/user/developer/bitdubai/version_1/AssetUserWalletModulePluginRoot.java
DAP/plugin/wallet_module/fermat-dap-plugin-wallet-module-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/module/asset/user/developer/bitdubai/version_1/structure/AssetUserWalletModule.java
DAP/plugin/wallet_module/fermat-dap-plugin-wallet-module-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/module/wallet/redeem/point/developer/bitdubai/version_1/AssetRedeemPointWalletModulePluginRoot.java

Asset User Wallet and Asset Redeem Point Wallet.

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-user-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/user_redemption/bitdubai/version_1/structure/DigitalAssetUserRedemptionVault.java
DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-user-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/user_redemption/bitdubai/version_1/structure/UserRedemptionRedeemer.java
DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-user-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/user_redemption/bitdubai/version_1/structure/UserRedemptionTransactionManager.java
DAP/plugin/network_service/fermat-dap-plugin-network-service-asset-transmission-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/network/service/asset/transmission/developer/bitdubai/version_1/AssetTransmissionNetworkServicePluginRoot.java

Integration Testing

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-redeem-point-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/digital_asset_transaction/redeem_point_redemption/bitdubai/version_1/structure/events/RedeemPointRedemptionMonitorAgent.java

Redeem Point Redemption

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-asset-appropriation-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/asset_appropiation/developer/bitdubai/version_1/structure/events/AssetAppropriationMonitorAgent.java

APpropriation

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-redeem-point-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/digital_asset_transaction/redeem_point_redemption/bitdubai/version_1/structure/events/RedeemPointRedemptionEventHandler.java
DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-redeem-point-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/digital_asset_transaction/redeem_point_redemption/bitdubai/version_1/structure/events/RedeemPointRedemptionRecorderService.java

Now RedeemPoint Redemption listens to his events.

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-redeem-point-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/digital_asset_transaction/redeem_point_redemption/bitdubai/version_1/structure/events/RedeemPointRedemptionMonitorAgent.java

Update the way Redeem Point Redemption looks for the crypto transaction.

---

DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-asset-reception-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/asset_reception/developer/bitdubai/version_1/structure/events/AssetReceptionMonitorAgent.java
DAP/plugin/digital_asset_transaction/fermat-dap-plugin-digital-asset-transaction-user-redemption-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/digital_asset_transaction/user_redemption/bitdubai/version_1/structure/events/UserRedemptionMonitorAgent.java

Now user redemption should successfully debit on book balance.

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/layout/dap_wallet_asset_issuer_asset_detail.xml
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_factory_bitdubai/adapters/AssetFactoryAdapter.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_factory_bitdubai/fragments/AssetEditorFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_factory_bitdubai/fragments/EditableAssetsFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/res/layout/asset_editor_fragment.xml
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/res/menu/asset_factory_main.xml
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/res/values/strings.xml
fermat-android-api/src/main/java/com/bitdubai/fermat_android_api/ui/Views/ConfirmDialog.java
fermat-android-api/src/main/res/layout/confirm_dialog.xml
fermat-android-core/src/main/java/com/bitdubai/android_core/app/StartActivity.java

- #4520 move delete option, show dialog at publish an asset and change bitcoins amount of assets in edit list.
- Fix #3657 change location of distribute and appropriate buttons

Develop #4520, Fix #3657

---

DAP/plugin/middleware/fermat-dap-plugin-middleware-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/middleware/asset/issuer/developer/bitdubai/version_1/structure/database/AssetFactoryMiddlewareDao.java

CHANGE: Change the way how we delete the asset factories, it wasn't deleting the contract associated with the factory, nor the resource.

FIX: a bug that won't delete an asset factory.

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/UserRedeemedListFragment.java
DAP/plugin/actor/fermat-dap-plugin-actor-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/actor/redeem/point/developer/bitdubai/version_1/structure/RedeemPointActorDao.java

show redeem point name in redeemed statistics and refresh

Fix #4608 issuer wallet

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/AssetDeliveryFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/holders/AssetDeliverySelectGroupsHolder.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/models/Data.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/models/Group.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetRedeemFragment.java

- set assets to delivery correctly when groups is selected
- show users count in group name row at select groups
- show images in delivery and redeem views
- show asset or assets remaining in delivery and redeem views

Fix #4610 changes in user and issuer wallets

---

DMP/plugin/engine/fermat-dmp-plugin-engine-sub-app-runtime-bitdubai/src/main/java/com/bitdubai/fermat_dmp_plugin/layer/engine/sub_app_runtime/developer/bitdubai/version_1/SubAppRuntimeEnginePluginRoot.java
PIP/android/sub_app/fermat-pip-android-sub-app-developer-bitdubai/src/main/java/com/bitdubai/sub_app/developer/fragment/DatabaseToolsDatabaseListFragment.java
PIP/android/sub_app/fermat-pip-android-sub-app-developer-bitdubai/src/main/java/com/bitdubai/sub_app/developer/fragment/DatabaseToolsDatabaseTableListFragment.java
PIP/android/sub_app/fermat-pip-android-sub-app-developer-bitdubai/src/main/java/com/bitdubai/sub_app/developer/fragment/DatabaseToolsFragment.java
fermat-api/src/main/java/com/bitdubai/fermat_api/layer/all_definition/navigation_structure/enums/Activities.java

remove log tools for the moment

Fix #4679 enchance navegability of databases and tables

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/common/adapters/MyAssetsAdapter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/common/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/MyAssetsActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/layout/dap_wallet_asset_issuer_asset_detail.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/menu/dap_asset_issuer_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/values/strings.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/adapters/MyAssetsAdapter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/UserMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_wallet_asset_user_asset_detail.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/menu/dap_wallet_asset_user_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/values/strings.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/adapters/MyAssetsAdapter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/RedeemPointMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/layout/dap_wallet_asset_redeem_point_detail.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/menu/dap_wallet_asset_redeem_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/values/strings.xml

- search by asset name in issuer, user and redeem point wallets
- ui enchance in asset detail view for large asset names

#4694 search by asset name in issuer, user and redeem point wallets

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/holders/AssetDetailTransactionHolder.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/models/Transaction.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_wallet_asset_user_transaction_item.xml

adding memo
replacing book > pending and available > confirmed

#4718 asset user wallet gui changes

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetSellFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_wallet_asset_user_asset_sell.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/values/strings.xml

remove total balance label
validate and call to module method

#4718 asset user wallet gui changes - sell asset

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetDetailTransactionsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetSellFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/models/SellInfo.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_wallet_asset_user_asset_detail_transaction.xml
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/all_definition/util/DAPStandardFormats.java

save entered data when an user is selected
load transactions on init view

#4718 asset user wallet gui changes - sell asset and transactions view

---

PIP/android/sub_app/fermat-pip-android-sub-app-developer-bitdubai/src/main/java/com/bitdubai/sub_app/developer/filters/DeveloperPluginFilter.java
PIP/android/sub_app/fermat-pip-android-sub-app-developer-bitdubai/src/main/java/com/bitdubai/sub_app/developer/fragment/DatabaseToolsFragment.java

enhanchements in developer tools

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/AssetDeliveryFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/AssetDeliverySelectGroupsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/AssetDeliverySelectUsersFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/MyAssetsActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/SettingsAssetIssuerFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/SettingsAssetIssuerNetworkFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/SettingsAssetIssuerNotificationFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/UserAppropiateListFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/UserDeliveryListFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/UserRedeemedListFragment.java

move Help menu to bottom and show text in all views

#4942 issuer wallet changes

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetDetailTransactionsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetRedeemFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetRedeemSelectRedeemPointsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetSellFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetSellSelectUserFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetTransferFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetTransferSelectUserFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/SettingsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/SettingsMainNetworkFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/SettingsNotificationsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/UserMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/RedeemPointDetailActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/RedeemPointDetailTransactionsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/RedeemPointMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/SettingsFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/SettingsMainNetworkFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/SettingsNotificationsFragment.java

move Help menu to bottom and show text in all views

#4718 user wallet changes

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/common/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_issuer_bitdubai/fragments/MyAssetsActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/menu/dap_asset_issuer_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/values/strings.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/UserMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/menu/dap_wallet_asset_user_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/values/strings.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/filters/MyAssetsAdapterFilter.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_redeem_point_bitdubai/fragments/RedeemPointMainActivityFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/menu/dap_wallet_asset_redeem_home_menu.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/values/strings.xml

change menu titles "show/hide empty assets" and hide by default

Fix #4694 dap wallets gui changes

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetNegotiationDetailFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/util/Utils.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_wallet_asset_user_asset_negotiation_detail.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/values/strings.xml
DAP/library/api/fermat-dap-api/src/main/java/com/bitdubai/fermat_dap_api/layer/dap_module/wallet_asset_user/interfaces/AssetUserWalletSubAppModuleManager.java
DAP/plugin/wallet_module/fermat-dap-plugin-wallet-module-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_plugin/layer/module/asset/user/developer/bitdubai/version_1/AssetUserWalletModulePluginRoot.java

show bitcoin wallet balance in buy view and validation

#4984 asset user gui changes

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetNegotiationDetailFragment.java
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_wallet_asset_user_bitdubai/fragments/AssetSellFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_factory_bitdubai/fragments/EditableAssetsFragment.java

- change validation of satoshis minimum amount (asset factory and sell asset)
- change activity to home in asset buyer

changes in asset factory and user wallet

---

DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-issuer-bitdubai/src/main/res/layout/dap_wallet_asset_issuer_asset_item.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-asset-user-bitdubai/src/main/res/layout/dap_v3_wallet_asset_user_card.xml
DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/layout/dap_wallet_asset_redeem_point_asset_item.xml
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_factory_bitdubai/fragments/AssetEditorFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-factory-bitdubai/src/main/res/layout/asset_editor_fragment.xml
DAP/android/sub_app/fermat-dap-android-sub-app-asset-issuer-identity-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_issuer_identity_bitdubai/fragments/CreateIssuerIdentityFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-asset-user-identity-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_asset_user_identity_bitdubai/fragments/CreateUserIdentityFragment.java
DAP/android/sub_app/fermat-dap-android-sub-app-redeem-point-identity-bitdubai/src/main/java/com/bitdubai/fermat_dap_android_sub_app_redeem_point_identity_bitdubai/fragments/CreateRedeemPointIdentityFragment.java

FIX problem load images all DAP 
FIX problem size of images all DAP keep proportion with rmultiples resolutions

Dap gui - Fix Details
